version: '3.8'

services:
  backend:
    build:
      context: ./auth-service
    container_name: auth-service
    expose:
      - "8080"
    networks:
      - backend-network

  frontend:
    image: nginx:latest
    container_name: nginx-api-gateway
    volumes:
      - ./api-gateway/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge